version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/NodeJS"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/Java"
    schedule:
       interval: "daily"
